---
title: "Leaflet"
author: "Eric Scuccimarra"
date: "15 January 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(leaflet)
```

## Leaflet

```{r createmap}
my_map <- leaflet() %>% addTiles() %>%  addMarkers(lat=46.23, lng=6.85, popup="Morgins")
my_map
```

## Multiple Markers
```{r multiplemarkers}
set.seed(2016-04-25)
df <- data.frame(lat = runif(20,min=39.2,max=39.3), lng = runif(20, min=-76.6,max=-76.5))

df %>% leaflet() %>% addTiles() %>% addMarkers()
```

## Mapping Clusters

```{r clusters}
df <- data.frame(lat = runif(500, min=39.25, max=39.35), lng=runif(500, min=-76.65, max=-76.55))

df %>% leaflet() %>% addTiles() %>% addMarkers(clusterOptions = markerClusterOptions())
```

## Custom Markers

```{r custommarkers}
sites <- c("<a href='http://ericscuccimarra.com'>Eric Scuccimarra</a>","<a href='http://morgins.ch'>Le telesiege</a>")
markers <- data.frame(lat = c(46.2373629, 46.23646669284622), lng = c(6.862394699999982, 6.858097314834595) )

markers %>% leaflet() %>% addTiles() %>% addMarkers(popup=sites)
```

## Circle Markers
```{r circlemarkers}
df <- data.frame(lat = runif(20, min=39.25, max=39.35), lng=runif(20, min=-76.65, max=-76.55))

df %>% leaflet() %>% addTiles() %>% addCircleMarkers()
```

## Drawing Circles
```{r circles}
df <- data.frame(lat = runif(20, min=39.25, max=39.35), lng=runif(20, min=-76.65, max=-76.55), col=sample(c("red", "blue", "green"), 20, replace=TRUE), pop=runif(20, min=800, max=2000), stringsAsFactors=FALSE)
df %>% leaflet() %>% addTiles() %>% addCircleMarkers(col=df$col) %>% addCircles(radius=df$pop, weight=1, col=df$col) %>% addLegend(labels=LETTERS[1:3], colors=c("red", "blue", "green"))
```